### ISSUE TITLE
fix (README.md): link to the example deployment is broken

### ISSUE THREAD

**Issue by wpannell** [rarmatei/egghead-thinking-reactively#1]
### [(README.md)](../blob/master/README.md)

...

[View example deployment here](https://vigilant-visvesvaraya-945613.netlify.com/)

...

Remarks: nice idea for a course/workshop

**Comment by rarmatei** [comment]
thanks so much for pointing this out!!!

I've changed the deployment link and pushed it out to all the branches! 👍
