### ISSUE TITLE
fix (lesson-10): dev environment does not behave as in the lesson

### ISSUE THREAD

**Issue by wpannell** [rarmatei/egghead-thinking-reactively#3]
Steps to reproduce:

```bash
git checkout lesson-10
npm install
npm start

# click any button multiple times
```

Effect: run time errors in the browser console.

**Comment by rarmatei** [comment]
really appreciate you reporting all these issues - this was also present in branches `lesson-08` and `lesson-09`

fix has been pushed and this should work now 👍

**Comment by wpannell** [comment]
@rarmatei thanks for addressing these issues.  Now, I'll pick up where I left off of this very useful training.

If I run into more issues, I'll report them back here.
